### ISSUE TITLE
Figure out how to test set_time

### ISSUE THREAD

**Issue by schneiderchristopher** [schneiderchristopher/lsr#4]
For now I can't test this function the way it is implement as I can't create a Metadata struct since its private.

https://github.com/schneiderchristopher/lsr/blob/01888b482db89e5695a2c3437a5a28ff80a5e919/src/path/paths.rs#L64-L81

**Comment by zihadmahiuddin** [comment]
I think instead of using `Metadata` you can use `SystemTime` and replace `metadata` with `metadata.modified()` where you call this function.
Then when testing, you can add a `Duration` to `SystemTime::UNIX_EPOCH` to get a specific time that you want to test with.
What do you think?

**Comment by schneiderchristopher** [comment]
Thanks! That was perfect.
Fixed on https://github.com/schneiderchristopher/lsr/commit/8c551cc5d14059e0b5c7b7f77d444e86df3e52c7
