### ISSUE TITLE
Handle UTC

### ISSUE THREAD

**Issue by schneiderchristopher** [schneiderchristopher/lsr#5]
Needs to get the correct time for every UTC, for now it only supports UTC-0

**Comment by zihadmahiuddin** [comment]
Do you mean showing the formatted time in the user's local timezone?

**Comment by schneiderchristopher** [comment]
Yes, for now it shows the time for UTC-0. If someone lives in UTC-3 it will be 3 hours different from the time displayed on the terminal when running the program
